# Generated by Django 2.2.4 on 2019-11-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.SmallIntegerField(default=1, verbose_name='删除状态')),
                ('title', models.CharField(max_length=50, verbose_name='书名')),
                ('auther', models.CharField(max_length=30, verbose_name='作者')),
                ('binding', models.CharField(max_length=20, verbose_name='精装')),
                ('publisher', models.CharField(max_length=50, verbose_name='出版商')),
                ('price', models.CharField(max_length=20, verbose_name='价格')),
                ('pages', models.IntegerField(verbose_name='页数')),
                ('pubdate', models.CharField(max_length=20, verbose_name='出版年')),
                ('isbn', models.CharField(max_length=15, unique=True, verbose_name='isbn')),
                ('summary', models.CharField(max_length=1000, verbose_name='内容简介')),
                ('image', models.CharField(max_length=50, verbose_name='封面')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
