# Generated by Django 2.2.4 on 2020-01-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookarticle',
            name='title',
            field=models.CharField(max_length=50, verbose_name='书语标题'),
        ),
    ]
