# Generated by Django 2.2.4 on 2020-02-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_articles', '0002_auto_20200119_0944'),
        ('book_articles', '0002_auto_20200202_1828'),
    ]

    operations = [
    ]
