# Generated by Django 2.2.4 on 2019-11-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191128_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='beans',
            field=models.FloatField(default=1, verbose_name='豆子'),
        ),
    ]
