# Generated by Django 2.2.4 on 2019-11-29 12:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'verbose_name': '礼物', 'verbose_name_plural': '礼物'},
        ),
        migrations.AlterUniqueTogether(
            name='gift',
            unique_together={('user', 'isbn')},
        ),
    ]
