# Generated by Django 2.2.4 on 2020-02-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0003_auto_20191220_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ('-create_time',), 'verbose_name': '消息', 'verbose_name_plural': '消息'},
        ),
        migrations.AlterUniqueTogether(
            name='gift',
            unique_together=set(),
        ),
    ]
