# Generated by Django 2.2.4 on 2020-02-07 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gift', '0004_auto_20200203_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ('-create_time',), 'verbose_name': '礼物', 'verbose_name_plural': '礼物'},
        ),
        migrations.AlterUniqueTogether(
            name='gift',
            unique_together={('user', 'isbn')},
        ),
    ]
