# Generated by Django 2.2.4 on 2019-11-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.SmallIntegerField(default=1, verbose_name='删除状态')),
                ('recipient_name', models.CharField(max_length=20, verbose_name='接受者姓名')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('message', models.CharField(max_length=200, verbose_name='留言')),
                ('mobile', models.CharField(max_length=20, verbose_name='手机')),
                ('isbn', models.CharField(max_length=13, verbose_name='isbn')),
                ('book_title', models.CharField(max_length=50, verbose_name='图书名')),
                ('book_author', models.CharField(max_length=30, verbose_name='图书书作者')),
                ('book_img', models.CharField(max_length=50, verbose_name='图书封面')),
                ('requester_id', models.IntegerField(verbose_name='发送者')),
                ('requester_nickname', models.IntegerField(verbose_name='发送者昵称')),
                ('gifter_id', models.IntegerField(verbose_name='送礼物人_id')),
                ('gift_id', models.IntegerField(verbose_name='礼物_id')),
                ('gifter_nickname', models.CharField(max_length=20, verbose_name='礼物者_昵称')),
                ('pending', models.SmallIntegerField(choices=[(1, 'wating'), (2, 'success'), (3, 'reject'), (4, 'redraw')], default=1, verbose_name='鱼漂状态')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
