# Generated by Django 2.2.4 on 2020-01-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0002_auto_20191201_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='drift',
            name='express_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drift',
            name='expressnumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='快递单号'),
        ),
    ]
